url: http://jkeravec.github.io
baseurl: ''
env: 'prod'

# Site settings
title: Julien Kéravec
email: jkeravec@gmail.com
description: "Webmaster, intégrateur HTML, développeur front end, réalisation création sites internet, redon"

# excerpt_separator: <!--more-->

google_analytics_id : UA-72727120-1


gems:
  - jekyll-sitemap

#sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  #style: :expanded
  #line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  #sourcemap: true

# Build settings
markdown: kramdown
permalink: pretty

#exclude: ["node_modules", "bower_components", "gulpfile.js", "package.json"]
exclude:
  - node_modules
  - bower_components
  - gulpfile.js
  - package.json
  - README.md
  - .sass-cache

# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ['<!-- ', ' -->']
  endings: all
  profile: false
  # startings: [html, head, body]
